In [1]:
import io
from IPython.nbformat import current
def execute_notebook(nbfile):
    with io.open(nbfile) as f:
        nb = current.read(f, 'json')
    ip = get_ipython()
    for cell in nb.worksheets[0].cells:
        if cell.cell_type != 'code':
            continue
        ip.run_cell(cell.input)
execute_notebook("/cellar/users/ramarty/Projects/kir/KIR_development/bin/imports.ipynb")
execute_notebook("/cellar/users/ramarty/Projects/kir/KIR_development/data_gathering/alternate/sample_mapping.ipynb")

/cellar/users/ramarty/anaconda/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated since IPython 4.0. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/cellar/users/ramarty/anaconda/lib/python2.7/site-packages/nbformat/current.py:19: UserWarning: nbformat.current is deprecated.

- use nbformat for read/write/validate public API
- use nbformat.vX directly to composing notebooks of a particular version

  """)

Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib

In [32]:
# import CIBERSORT data
cibersort = pd.read_csv('/cellar/users/ramarty/Data/hla_ii/generated_data/cibersort.csv', index_col=0)

In [33]:
cf_dfs = []
for j in range(0, 10000, 1000):
    cf_dfs.append(pd.read_csv('/cellar/users/ramarty/Data/kir/biological/tumor_infiltration/cell_fractions/cf.{0}_{1}.csv'.format(str(j), str(j+1000)), sep=' '))
epic = pd.concat(cf_dfs)

In [34]:
def convert_barcode(x):
    return '-'.join(x.split('.'))
epic.index = [convert_barcode(x) for x in epic.index]

In [35]:
epic.head()

,Bcells,CAFs,CD4_Tcells,CD8_Tcells,Endothelial,Macrophages,NKcells,otherCells
TCGA-J2-8192,9.671475e-10,1.000000,3.193152e-09,1.625073e-07,3.295552e-09,9.425435e-10,1.476839e-07,2.427621e-08
TCGA-CJ-4885,8.830383e-03,0.026095,1.306955e-01,6.623689e-02,4.713806e-01,5.954193e-03,1.411672e-08,2.908071e-01
TCGA-AS-3777,1.281063e-03,0.036519,7.492079e-02,6.717817e-07,1.548351e-01,7.473688e-02,1.079336e-08,6.577062e-01
TCGA-80-5611,2.884894e-03,0.111510,8.243891e-02,1.799877e-06,2.633577e-02,3.589989e-02,1.849761e-09,7.409288e-01
TCGA-A8-A06R,1.042939e-02,0.732772,8.905182e-03,8.873437e-07,1.174448e-01,7.061846e-03,1.130674e-04,1.232727e-01

In [36]:
epic.to_csv('/cellar/users/ramarty/Data/hla_ii/generated_data/epic.csv')

In [37]:
infiltration = pd.merge(cibersort, epic, left_index=True, right_index=True)

In [38]:
clinical = pd.read_csv('/cellar/users/ramarty/Data/kir/TCGA/clinical_df.csv', index_col=0)

In [39]:
clinical.head()

,age_at_diagnosis,days_to_death,days_to_last_followup,ethnicity,gender,race,tissue,vital_status
TCGA-02-0001,44,358,279.0,NOT HISPANIC OR LATINO,FEMALE,WHITE,GBM,Dead
TCGA-02-0003,50,144,144.0,NOT HISPANIC OR LATINO,MALE,WHITE,GBM,Dead
TCGA-02-0004,59,345,345.0,NOT HISPANIC OR LATINO,MALE,WHITE,GBM,Dead
TCGA-02-0006,56,558,558.0,NOT HISPANIC OR LATINO,FEMALE,WHITE,GBM,Dead
TCGA-02-0007,40,705,705.0,NOT HISPANIC OR LATINO,FEMALE,WHITE,GBM,Dead

In [40]:
# need to figure out where this file is coming from... it has the barcodes as the indices
#types = pd.read_csv('/cellar/users/ramarty/Data/kir/TCGA/data_frames/TCGA.gene_copy_numbers.kir_mean.csv',
#                    index_col=0)
types = pd.read_csv('/cellar/users/ramarty/Data/kir/TCGA/data_frames/TCGA.gene_copy_numbers.kir_mean.excluded_close_boundaries.csv',
                    index_col=0)

In [41]:
types.head()

,KIR3DL3,KIR3DP1,KIR2DL4,KIR3DL2,KIR2DP1,KIR2DL1,KIR2DS4,KIR2DS3,KIR2DS2,KIR2DS5,KIR3DS1,KIR2DS1,KIR2DL2,KIR3DL1,KIR2DL3,KIR2DL5A
TCGA-02-0003,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2,0.0
TCGA-02-0033,2.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1,1.0
TCGA-02-0047,2.0,2.0,2.0,2.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,1,0.0
TCGA-02-0055,2.0,2.0,2.0,2.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,1,0.0
TCGA-02-2470,2.0,2.0,2.0,2.0,2.0,2.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,2,1.0

In [42]:
types.KIR2DL1.value_counts()

2.0    2909
1.0    1293
3.0     335
0.0     154
Name: KIR2DL1, dtype: int64

In [43]:
# Import HLA types
hla = pd.read_csv('/cellar/users/ramarty/Data/kir/biological/hla_types.csv', index_col=0)

In [44]:
# format it correctly
hla.head()

                A1    A2    B1    B2    C1    C2
barcode
TCGA-QT-A5XO  A*66  A*02  B*35  B*15  C*03  C*07
TCGA-78-7159  A*02  A*68  B*14  B*44  C*07  C*08
TCGA-DU-6400  A*01  A*34  B*08  B*27  C*02  C*07
TCGA-12-0656  A*30  A*03  B*42  B*53  C*17  C*04
TCGA-50-6591  A*25  A*25     -  B*44  C*12  C*05

In [45]:
# gotta extend the typing
len(types), len(clinical), len(infiltration), len(hla)

(4717, 10959, 9657, 8359)

Sort types within each gene

In [46]:
new_matrix = []
for y in hla.ix[:, :].iterrows():
    x = y[1]
    new_array = []
    # hla a
    if x[0] > x[1]:
        new_array.append(x[1])
        new_array.append(x[0])
    else:
        new_array.append(x[0])
        new_array.append(x[1])
    # hla b
    if x[2] > x[3]:
        new_array.append(x[3])
        new_array.append(x[2])
    else:
        new_array.append(x[2])
        new_array.append(x[3])
    # hla c
    if x[4] > x[5]:
        new_array.append(x[5])
        new_array.append(x[4])
    else:
        new_array.append(x[4])
        new_array.append(x[5])
    new_matrix.append(new_array)

/cellar/users/ramarty/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [47]:
hla_types = pd.DataFrame(new_matrix)
hla_types.index = hla.index

In [48]:
hla_types.columns = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2']

In [49]:
hla_fd = pd.read_csv('/cellar/users/ramarty/Data/kir/biological/hla_types.four_digit.csv', index_col=0)

In [50]:
new_matrix = []
for y in hla_fd.ix[:, :].iterrows():
    x = y[1]
    new_array = []
    # hla a
    if x[0] > x[1]:
        new_array.append(x[1])
        new_array.append(x[0])
    else:
        new_array.append(x[0])
        new_array.append(x[1])
    # hla b
    if x[2] > x[3]:
        new_array.append(x[3])
        new_array.append(x[2])
    else:
        new_array.append(x[2])
        new_array.append(x[3])
    # hla c
    if x[4] > x[5]:
        new_array.append(x[5])
        new_array.append(x[4])
    else:
        new_array.append(x[4])
        new_array.append(x[5])
    new_matrix.append(new_array)

/cellar/users/ramarty/anaconda/lib/python2.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [51]:
hla_types_fd = pd.DataFrame(new_matrix)
hla_types_fd.index = hla.index

In [52]:
hla_types_fd.columns = ['A1_', 'A2_', 'B1_', 'B2_', 'C1_', 'C2_']

In [53]:
merged = pd.merge(pd.merge(pd.merge(pd.merge(types, clinical, left_index=True, right_index=True), 
    infiltration, left_index=True, right_index=True), 
                           hla_types, left_index=True, right_index=True), 
                  hla_types_fd, left_index=True, right_index=True)
#merged = pd.merge(pd.merge(types, clinical, left_index=True, right_index=True), 
#                           cibersort, left_index=True, right_index=True)

In [54]:
print len(merged)
merged.head()

3501

,KIR3DL3,KIR3DP1,KIR2DL4,KIR3DL2,KIR2DP1,KIR2DL1,KIR2DS4,KIR2DS3,KIR2DS2,KIR2DS5,...,B1,B2,C1,C2,A1_,A2_,B1_,B2_,C1_,C2_
TCGA-02-0047,2.0,2.0,2.0,2.0,1.0,1.0,2.0,0.0,1.0,0.0,...,B*15,B*15,C*03,C*03,A*02:01,A*32:01,B*15:01,B*15:01,C*03:03,C*03:03
TCGA-02-0055,2.0,2.0,2.0,2.0,1.0,1.0,2.0,0.0,1.0,0.0,...,B*51,B*55,C*03,C*15,A*11:01,A*31:01,B*51:01,B*55:01,C*03:03,C*15:02
TCGA-02-2483,3.0,3.0,3.0,3.0,3.0,3.0,0.0,0.0,0.0,3.0,...,B*07,B*52,C*07,C*12,A*03:01,A*11:01,B*07:02,B*52:01,C*07:02,C*12:02
TCGA-02-2485,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,...,B*44,B*49,C*07,C*16,A*03:01,A*29:02,B*44:04,B*49:01,C*07:01,C*16:01
TCGA-02-2486,3.0,3.0,3.0,3.0,0.0,0.0,3.0,0.0,3.0,0.0,...,B*07,B*07,C*07,C*07,A*03:01,A*03:01,B*07:02,B*07:02,C*07:02,C*07:02

In [55]:
merged.columns

Index([u'KIR3DL3', u'KIR3DP1', u'KIR2DL4', u'KIR3DL2', u'KIR2DP1', u'KIR2DL1',
       u'KIR2DS4', u'KIR2DS3', u'KIR2DS2', u'KIR2DS5', u'KIR3DS1', u'KIR2DS1',
       u'KIR2DL2', u'KIR3DL1', u'KIR2DL3', u'KIR2DL5A', u'age_at_diagnosis',
       u'days_to_death', u'days_to_last_followup', u'ethnicity', u'gender',
       u'race', u'tissue', u'vital_status', u'B cells naive',
       u'B cells memory', u'Plasma cells', u'T cells CD8',
       u'T cells CD4 naive', u'T cells CD4 memory resting',
       u'T cells CD4 memory activated', u'T cells follicular helper',
       u'T cells regulatory (Tregs)', u'T cells gamma delta',
       u'NK cells resting', u'NK cells activated', u'Monocytes',
       u'Macrophages M0', u'Macrophages M1', u'Macrophages M2',
       u'Dendritic cells resting', u'Dendritic cells activated',
       u'Mast cells resting', u'Mast cells activated', u'Eosinophils',
       u'Neutrophils', u'P-value', u'Pearson Correlation', u'RMSE', u'Bcells',
       u'CAFs', u'CD4_Tcells', u'CD8_Tcells', u'Endothelial', u'Macrophages',
       u'NKcells', u'otherCells', u'A1', u'A2', u'B1', u'B2', u'C1', u'C2',
       u'A1_', u'A2_', u'B1_', u'B2_', u'C1_', u'C2_'],
      dtype='object')

In [56]:
activating = ['KIR2DS1', 'KIR2DS2', 'KIR2DS3', 'KIR2DS4', 'KIR2DS5', 'KIR3DS1', 'KIR2DL4']
inhibitory = ['KIR2DL1', 'KIR2DL2', 'KIR2DL3', 'KIR3DL1', 'KIR3DL2', 'KIR3DL3', 'KIR2DL5A', 'KIR2DL4']

In [57]:
merged['activating'] = merged[activating].sum(axis=1)
merged['inhibitory'] = merged[inhibitory].sum(axis=1)

In [58]:
merged['ratio'] = merged.activating/merged.inhibitory

In [59]:
merged.head()

,KIR3DL3,KIR3DP1,KIR2DL4,KIR3DL2,KIR2DP1,KIR2DL1,KIR2DS4,KIR2DS3,KIR2DS2,KIR2DS5,...,C2,A1_,A2_,B1_,B2_,C1_,C2_,activating,inhibitory,ratio
TCGA-02-0047,2.0,2.0,2.0,2.0,1.0,1.0,2.0,0.0,1.0,0.0,...,C*03,A*02:01,A*32:01,B*15:01,B*15:01,C*03:03,C*03:03,5.0,11.0,0.454545
TCGA-02-0055,2.0,2.0,2.0,2.0,1.0,1.0,2.0,0.0,1.0,0.0,...,C*15,A*11:01,A*31:01,B*51:01,B*55:01,C*03:03,C*15:02,5.0,11.0,0.454545
TCGA-02-2483,3.0,3.0,3.0,3.0,3.0,3.0,0.0,0.0,0.0,3.0,...,C*12,A*03:01,A*11:01,B*07:02,B*52:01,C*07:02,C*12:02,10.0,17.0,0.588235
TCGA-02-2485,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,...,C*16,A*03:01,A*29:02,B*44:04,B*49:01,C*07:01,C*16:01,4.0,12.0,0.333333
TCGA-02-2486,3.0,3.0,3.0,3.0,0.0,0.0,3.0,0.0,3.0,0.0,...,C*07,A*03:01,A*03:01,B*07:02,B*07:02,C*07:02,C*07:02,9.0,15.0,0.600000

In [60]:
merged.tissue.value_counts()

LGG     453
HNSC    408
THCA    398
LUAD    368
PRAD    287
STAD    234
LUSC    233
BLCA    187
PCPG    148
OV      134
GBM     131
KIRC    128
PAAD    104
KIRP     76
SKCM     68
UVM      58
UCS      49
CESC     37
Name: tissue, dtype: int64

In [61]:
#merged.to_csv('/cellar/users/ramarty/Data/kir/TCGA/data_frames/all_the_good_stuff.csv')
merged.to_csv('/cellar/users/ramarty/Data/kir/TCGA/data_frames/all_the_good_stuff.excluded_close_boundaries.csv')

Add neoantigen features to all_the_good_stuff

In [36]:
# import dataframe
presentation = pd.read_csv('/cellar/users/ramarty/Data/immune_evasion/data_frames/merged.csv', index_col=0)

/cellar/users/ramarty/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2868: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [37]:
presentation.head()

,Tumor_Sample_Barcode,aa_change,mutation,valid,neoantigens,hugo_symbol,MLE_CCF,CI_l,CI_h,swanton_clonal,...,start_position,end_position,strand,seq_effect,ref_read_count,alt_read_count,vaf,aa_tumor,aa_ref,amplified
0,TCGA-05-4244,ARHGEF10L.pP964A,ARHGEF10L_P964A,True,6,ARHGEF10L,0.230230,0.082082,0.588589,False,...,17990971,17990971,1,missense_mutation,26.0,3.0,0.103,A,P,False
1,TCGA-05-4244,HTR6.pA263G,HTR6_A263G,True,2,HTR6,0.418418,0.264264,0.631632,False,...,20005133,20005133,1,missense_mutation,69.0,16.0,0.188,G,A,False
2,TCGA-05-4244,NR0B2.pP80S,NR0B2_P80S,True,0,NR0B2,1.000000,NaN,NaN,True,...,27240194,27240194,-1,missense_mutation,9.0,8.0,0.471,S,P,True
3,TCGA-05-4244,AHDC1.pT1358I,AHDC1_T1358I,True,1,AHDC1,0.561562,0.393393,0.768769,False,...,27874554,27874554,-1,missense_mutation,74.0,25.0,0.253,I,T,False
4,TCGA-05-4244,C1orf177.pR287G,C1orf177_R287G,True,0,C1orf177,0.485485,0.351351,0.650651,False,...,55279583,55279583,1,missense_mutation,111.0,31.0,0.218,G,R,False

In [38]:
# what is the overlap in patients between the joris set and my set?
#print len(merged.index)
#print len(list(presentation.Tumor_Sample_Barcode.unique()))
#print len([x for x in merged.index if x in list(presentation.Tumor_Sample_Barcode.unique())])

In [39]:
# clean up dataframe
presentation = presentation[presentation.neoantigens != '-']
presentation.neoantigens = presentation.neoantigens.astype(int)

In [40]:
# create features
total_presented_peptides = presentation[['Tumor_Sample_Barcode', 'neoantigens']].groupby('Tumor_Sample_Barcode').sum().reset_index()
total_presented_peptides.columns = ['Tumor_Sample_Barcode', 'total_presented_peptides']

In [41]:
mutation_count = presentation[['Tumor_Sample_Barcode', 'neoantigens']].groupby('Tumor_Sample_Barcode').count().reset_index()
mutation_count.columns = ['Tumor_Sample_Barcode', 'mutation_count']

In [42]:
max_neoantigen = presentation[['Tumor_Sample_Barcode', 'neoantigens']].groupby('Tumor_Sample_Barcode').max().reset_index()
max_neoantigen.columns = ['Tumor_Sample_Barcode', 'max_neoantigen']

In [43]:
num_neoantigens1 = presentation[presentation.neoantigens>1][['Tumor_Sample_Barcode', 'neoantigens']].groupby('Tumor_Sample_Barcode').count().reset_index()
num_neoantigens1.columns = ['Tumor_Sample_Barcode', 'num_neoantigens1']
num_neoantigens5 = presentation[presentation.neoantigens>5][['Tumor_Sample_Barcode', 'neoantigens']].groupby('Tumor_Sample_Barcode').count().reset_index()
num_neoantigens5.columns = ['Tumor_Sample_Barcode', 'num_neoantigens5']
num_neoantigens10 = presentation[presentation.neoantigens>10][['Tumor_Sample_Barcode', 'neoantigens']].groupby('Tumor_Sample_Barcode').count().reset_index()
num_neoantigens10.columns = ['Tumor_Sample_Barcode', 'num_neoantigens10']

In [44]:
## merge features
neoantigen_features0 = pd.merge(pd.merge(total_presented_peptides, mutation_count, on='Tumor_Sample_Barcode'),
                               pd.merge(max_neoantigen, num_neoantigens1, on='Tumor_Sample_Barcode'), on='Tumor_Sample_Barcode')
neoantigen_features = pd.merge(pd.merge(num_neoantigens5, num_neoantigens10, on='Tumor_Sample_Barcode'), neoantigen_features0, on='Tumor_Sample_Barcode')

In [45]:
neoantigen_features.index = neoantigen_features.Tumor_Sample_Barcode

In [46]:
neoantigen_features.head()

,Tumor_Sample_Barcode,num_neoantigens5,num_neoantigens10,total_presented_peptides,mutation_count,max_neoantigen,num_neoantigens1
Tumor_Sample_Barcode,,,,,,,
TCGA-05-4244,TCGA-05-4244,65,19,863,200,31,130
TCGA-05-4249,TCGA-05-4249,72,29,1171,303,24,193
TCGA-05-4250,TCGA-05-4250,99,25,1465,349,29,244
TCGA-05-4384,TCGA-05-4384,39,14,586,136,53,78
TCGA-05-4390,TCGA-05-4390,175,62,2476,555,34,369

In [47]:
# output again
merged = pd.merge(neoantigen_features, merged, left_index=True, right_index=True)

In [48]:
merged.head()

,Tumor_Sample_Barcode,num_neoantigens5,num_neoantigens10,total_presented_peptides,mutation_count,max_neoantigen,num_neoantigens1,KIR2DP1,KIR2DS4,KIR2DS5,...,C2,A1_,A2_,B1_,B2_,C1_,C2_,activating,inhibitory,ratio
TCGA-05-4244,TCGA-05-4244,65,19,863,200,31,130,1,1,1,...,C*17,A*01:01,A*02:02,B*41:01,B*52:01,C*12:02,C*17:01,9,11,0.818182
TCGA-05-4250,TCGA-05-4250,99,25,1465,349,29,244,2,2,0,...,C*06,A*01:01,A*11:01,B*45:01,B*57:01,C*06:02,C*06:02,4,12,0.333333
TCGA-05-4384,TCGA-05-4384,39,14,586,136,53,78,2,2,0,...,C*12,A*02:01,A*23:01,B*37:01,B*39:06,C*06:02,C*12:03,4,12,0.333333
TCGA-05-4390,TCGA-05-4390,175,62,2476,555,34,369,2,1,1,...,C*07,A*01:01,A*02:01,B*07:02,B*08:01,C*07:01,C*07:02,6,13,0.461538
TCGA-05-4396,TCGA-05-4396,135,41,2015,488,25,330,2,0,1,...,C*07,A*01:01,A*02:01,B*08:01,B*40:01,C*03:04,C*07:01,5,12,0.416667

In [49]:
merged.columns

Index([u'Tumor_Sample_Barcode', u'num_neoantigens5', u'num_neoantigens10',
       u'total_presented_peptides', u'mutation_count', u'max_neoantigen',
       u'num_neoantigens1', u'KIR2DP1', u'KIR2DS4', u'KIR2DS5', u'KIR2DS2',
       u'KIR2DS3', u'KIR2DS1', u'KIR2DL3', u'KIR2DL2', u'KIR2DL1', u'KIR2DL4',
       u'KIR3DS1', u'KIR3DL1', u'KIR3DL2', u'KIR3DL3', u'KIR2DL5A', u'KIR3DP1',
       u'Sample', u'barcode', u'age_at_diagnosis', u'days_to_death',
       u'days_to_last_followup', u'ethnicity', u'gender', u'race', u'tissue',
       u'vital_status', u'Bcells', u'Monocytes', u'Neutrophils', u'NKcells',
       u'Tcells', u'unkCells', u'A1', u'A2', u'B1', u'B2', u'C1', u'C2',
       u'A1_', u'A2_', u'B1_', u'B2_', u'C1_', u'C2_', u'activating',
       u'inhibitory', u'ratio'],
      dtype='object')

In [50]:
capture_kit = pd.read_csv('/cellar/users/ramarty/Data/kir/TCGA/data_frames/all_samples.with_capture_kit.immort.csv', index_col=0)[['barcode', 'capture_kit']]
capture_kit.columns = ['Tumor_Sample_Barcode', 'capture_kit']

In [51]:
merged = pd.merge(merged, capture_kit, on='Tumor_Sample_Barcode', how='left')

In [52]:
merged.to_csv('/cellar/users/ramarty/Data/kir/biological/all_the_good_stuff.csv')